[package]
name = "rocket_test"
version = "0.1.0"
authors = ["Tommy Malmqvist <tommy.malmqvist@codelabs.se>"]
edition = "2018"

[timereport_api]
name = "timereport_api"
path = "src/timereport_api.rs"

[dependencies]
rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
api = { path = "../api" }