[package]
name = "api"
version = "0.1.0"
authors = ["Tommy Malmqvist <tommy.malmqvist@codelabs.se>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
slack = { path = "../slack" }